### ISSUE TITLE
this.caster = null

### ISSUE THREAD

**Issue by wmurphyrd** [wmurphyrd/aframe-super-hands-component#109]
Error when loading progressive controls if controllers are active at load

**Comment by wmurphyrd** [comment]
This is caused by a workaround for an A-Frame issue that is fixed on master. Will probably just wait until A-Frame v0.8.0 drops and remove the workaround

**Comment by PButcher** [comment]
Still seems to be apparent on the master branch unless I'm getting `this.caster = null` for some other bizarre reason.

**Comment by wmurphyrd** [comment]
Oh yeah the error will continue to happen for now, but, it is caused by a bit of workaround code that will be obsolete once A-Frame v0.8.0 is out, so I'm inclined to just wait till then and delete the workaround code rather than put more effort into improving the deprecated workaround. 

In all of my experience, this receiving error has no impact on `super-hands` functionality. If you're experiencing something different, let me know and I'll increase the priority of this.

**Comment by PButcher** [comment]
Ah I understand now, sorry.

It doesn't cause me any issues, it just pops up every time the page reloads and the controllers are active.
