### ISSUE TITLE
TypeError: Cannot read property 'children' of undefined - progressive-controls

### ISSUE THREAD

**Issue by superjose** [wmurphyrd/aframe-super-hands-component#116]
Jeez, I was banging my head for a while on this one. Again, William, thanks for all the help. This problem popped up when you [suggested me doing the following:](https://github.com/wmurphyrd/aframe-super-hands-component/issues/115#issuecomment-347413127)

`<a-entity progressive-controls="objects: [grabbable], [hoverable]"></a-entity>`

Out of the sudden, I started receiving: 

> raycaster.js:136 Uncaught TypeError: Cannot read property 'children' of undefined
>     at i.refreshObjects (raycaster.js:136)
>     at i.refreshObjects (bind.js:12)
>     at i.update (raycaster.js:73)
>     at i.updateProperties (component.js:259)
>     at i.module.exports.Component (component.js:50)
>     at new i (component.js:449)
>     at HTMLElement.value (a-entity.js:391)
>     at HTMLElement.value (a-entity.js:558)
>     at HTMLElement.Object.create.updateComponents.value (a-entity.js:525)
>     at HTMLElement.value (a-entity.js:672)

This left the gazer completely wasted, in the sense that I couldn't select or grab/drag anything with it.

After carefully debugging with Chrome, I found out that the problem was the mixins:
I was assigning to the mixins the grabbable, hoverable, stretchable attributes, like this:

```
 <a-mixin id="electron" geometry="primitive: sphere; radius:0.125;" 
            hoverable grabbable stretchable draggable droppable
            material="color: #e53935;"
            radius="0.125" particle-charge="electron"
            sleepy="angularDamping: 0; speedLimit: 1"
            collision-filter="group: particles; collidesWith: particles"
            >
```

But, I was telling progressive-controls to fetch **all the elements** that had hoverable grabbable stretchable, etc. (See first snippet above).

When progressive-controls passes it to the raycaster, it also passes the mixins I had defined (because they match the selector). The raycaster looks into the object3D property and fetches the children contained in them. Since mixins are an empty a-entity, they do not possess an object3D property. Hence, it throws the error. 

The solution is to _**use another selector that does not target the mixins.**_ . Doing so, will successfully parse the elements when they go to the raycaster.

I just wanted to let you know about this caveat, and if someone else runs into this problem, he/she can find a solution to it. 

Again, thank you very much!!!

**Comment by wmurphyrd** [comment]
I've been stuck on the same issue before. Is is frustrating! Sorry it happened to you, too. I just filed with the A-Frame repo to see if they would be interested in addressing this in the core.

**Comment by superjose** [comment]
Oh worry not! The apologies should be mine! Again, thanks a bunch for all the help! 
Absolutely, hopefully they can fix it for the next release ;)
