### ISSUE TITLE
manually determining interaction level

### ISSUE THREAD

**Issue by gabrieljbaker** [wmurphyrd/aframe-super-hands-component#119]
We want to use "gaze mode" on desktops in that have an HMD connected but are not in VR mode! Right now, as soon as the world loads (even before we enter VR mode), it's going to touch mode, not letting us use the gaze-based cursor when an HMD is connected.

We want it to switch to touch mode, but only AFTER we press the "enter VR" button.

We've tried this, but this isn't working: 

document.querySelector('a-scene').addEventListener('enter-vr', function () {
           var player = document.querySelector("#player");
           player.setAttribute("progressive-controls", "maxLevel", "touch"); });

**Comment by wmurphyrd** [comment]
The `progressive-controls.update` method needs to be modified to handle this case (also maybe what you describe should be the default behavior). 

As a workaround to use until `super-hands` is update to resolve the issue, you can simulate the events from the last controller connection after changing the `maxLevel` attribute. 

```js
var player = document.querySelector("#player");
player.setAttribute("progressive-controls", "maxLevel", "touch");
var controllerHistory = player.components['progressive-controls'].controllerName
player.emit('controllerconnected', {name: controllerHistory.get('right'), component: {data: {hand: 'right'}}})
player.emit('controllerconnected', {name: controllerHistory.get('left'), component: {data: {hand: 'left'}}})
```

**Comment by gabrieljbaker** [comment]
Thanks for this fix @wmurphyrd , that worked nicely.
