### ISSUE TITLE
After moving around on Desktop mode then entering VR-Mode, Controllers At Wrong Place

### ISSUE THREAD

**Issue by gabrieljbaker** [wmurphyrd/aframe-super-hands-component#120]
The use case I'm targeting here is one where users start out on desktop mode, move around a bit, and then enter VR mode once they've done a few things to the environment.

Right now when I start on desktop mode, Super-Hands seems to create the VR controllers for me even though I'm not using them. Once I move around on desktop and then hit the "Enter-VR" button, the controllers remain at the origin point. I see them moving when I wave the controllers around, but they seem to be stuck to the origin point and not linked to the player.

Curious for your thoughts @wmurphyrd  - I could just be doing something wrong.

**Comment by gabrieljbaker** [comment]
<a-entity id = "player" networked="template:#empty-template; showLocalTemplate: false" progressive-controls="maxLevel: gaze" >
       <a-camera id = "playercamera" networked="template:#head-template; showLocalTemplate: false">
         <a-entity class="gazecaster" cursorcontroller playercontroller ></a-entity>
       </a-camera>
     
      <a-entity  class="right-controller" networked="template:#right-hand-template; showLocalTemplate: true" ></a-entity>
      <a-entity  class="left-controller" networked="template:#right-hand-template; showLocalTemplate: true" ></a-entity>
  </a-entity>

**Comment by PButcher** [comment]
It's not just you, I replicated it in a blank scene, including after moving the camera in the A-Frame Inspector.

**Comment by wmurphyrd** [comment]
`wasd-controls` moves the camera independently from the rest of the player avatar structure, so it's creating an offset between the camera/hmd and controllers. 

I wonder if we can just put `wasd-controls` on the top level `progressive-controls` instead of the camera

**Comment by wmurphyrd** [comment]
This seems to do the trick:

```html
      <a-entity progressive-controls look-controls wasd-controls>
        <a-entity camera="userHeight: 1.6">
          <a-entity class="gazecaster"></a-entity>
        </a-entity>
        <a-entity class="right-controller"></a-entity>
        <a-entity class="left-controller"></a-entity>
      </a-entity>
```

Try it: https://glitch.com/edit/#!/right-grouse?path=index.html:1:0

I think I should make this the default

**Comment by gabrieljbaker** [comment]
@wmurphyrd Thanks for the quick action on this! Very excited to try it out. 

@PButcher Thanks for the thoughts! I'm still not fully sold on a-locomotor but I do want to use teleport controls in VR to move around. Have you implemented teleport controls with super-hands?

**Comment by PButcher** [comment]
@gabrieljbaker No, but it should be an easy thing to test with the preexisting `aframe-teleport-controls` component: https://github.com/fernandojsg/aframe-teleport-controls/

Append the `teleport-controls` component to either of your controllers and see.

**Comment by wmurphyrd** [comment]
Hey check it out, they're fixing this for us! aframevr/aframe#3394
