### ISSUE TITLE
Not able to move entities with obj-model

### ISSUE THREAD

**Issue by TitikshaDaga** [wmurphyrd/aframe-super-hands-component#122]
Hi,
I am trying to move an entity with obj-model with super hands component but not able to do so. Here is the code :
` <a-scene>
    <a-entity cubemap="folder: assets/imgs/"></a-entity>
    <a-assets>
      <a-asset-item id="lamp" src="assets/imgs/Lamp.obj"></a-asset-item>
    </a-assets>
  <a-assets></a-assets>
   <a-entity progressive-controls="objects: a-entity"></a-entity>
   <a-entity dynamic-body="mass:5;gravity:0;linearDamping:0.01;angularDamping:0.01;shape:auto;" width="1" height="1" depth="1" hoverable stretchable draggable dropppable clickable obj-model="obj:#lamp" scale="0.001 0.001 0.001" position="0 -1 -2"></a-entity>
   </a-scene>`
Please help!!

**Comment by wmurphyrd** [comment]
Hi. Your entity is not configured to be movable as it does not have the `grabbable` attribute. Try replacing `clickable` with `grabbable`. 

Please join us on slack for additional help: https://aframevr-slack.herokuapp.com/

**Comment by TitikshaDaga** [comment]
I tried adding the clickable attribute and still the same issue.....I also added the attribute grabbable instead and still the same issue

**Comment by TitikshaDaga** [comment]
I tried adding the clickable attribute and still the same issue.....I also added the attribute grabbable instead and still the same issue

**Comment by wmurphyrd** [comment]
Looking forward to seeing your post on slack so I can provide additional troubleshooting help
