### ISSUE TITLE
Examples do not work with Edge, Windows Creator Update, HP Mixed Reality Set

### ISSUE THREAD

**Issue by wassx** [wmurphyrd/aframe-super-hands-component#123]
Hi!
I was stumbling about this very promising library and really wanted to give it a try.
Sadly I'm not able to run the examples (physics).
My controllers are visible but no lasers on the tips of the controllers.
I'm not able to grab anything, just move my controllers and my head.
Any ideas please?

**Comment by wmurphyrd** [comment]
Does the laser pointer example work? https://wmurphyrd.github.io/aframe-super-hands-component/examples/mouse/

**Comment by wassx** [comment]
Ah ok, this one works, despite an offset to the hands. They appear ~2 meters in front of me.
But lasers are visible and dragging/resizing works too.

**Comment by wmurphyrd** [comment]
Thanks for the feedback, I might need to tweak the model offsets, but I haven't had my hands on any Windows MR kits yet. In the physics example, instead of lasers you're supposed to walk over and pick things up directly. Does that work and were the hands in the correct spot?

**Comment by wmurphyrd** [comment]
I finally got a chance to test with WinMR on Edge and everything works perfectly. Please report back if you continue to have issues
