### ISSUE TITLE
Oculus Controllers Overlap

### ISSUE THREAD

**Issue by aziliak** [wmurphyrd/aframe-super-hands-component#128]
When using the latest version of A-Frame (https://aframe.io/releases/0.8.0/aframe.min.js), the Oculus Rift controllers overlap for me and I'm only able to use the left controller.  If I switch back the previous version of A-FRAME the controllers work fine.

![image](https://user-images.githubusercontent.com/12801295/37332618-2aeaf592-2675-11e8-83ad-1c3d07d88041.png)

Anyone else having this issue?

**Comment by wmurphyrd** [comment]
Have you tried with the master branch version of `super-hands` I put up this Sunday?

**Comment by aziliak** [comment]
Using the master branch version, my rift controllers display as gearvr controller I believe and only the left controller is available to use.

![image](https://user-images.githubusercontent.com/12801295/37366041-4cde9570-26cd-11e8-8cc9-ac494dfdb8f2.png)

**Comment by PButcher** [comment]
This is an issue with the `laser-controls` component in 0.8.0 with Oculus Touch. I'll open up an issue in the aframe repo but here's a list of issues I'm currently experiencing with `laser-controls` and subsequently `progressive-controls` in 0.8.0 with Touch:

- Only the left controller is ever tracked
- When the left controller is tracked, the right controller is attached to the left controller
- Supplying the controller with any custom `raycaster` properties stops the controller from being tracked (it just sits in its default position in the scene).

Occassionally with certain raycaster properties set `progressive-controls` and `laser-controls`are serving me the GearVR controller.

**Comment by wmurphyrd** [comment]
Thanks for the feedback.

I'm having the same issue with Vive where I sometimes get that other controller model (And sometimes get invisible vive wands: aframevr/aframe#3441)

 `super-hands` is no longer using `laser-controls`, but instead adds all of the controller components directly, so it must be something that both have in common.

**Comment by WellanDraco** [comment]
Same issue when using the CV1 remote,
even if i dont have 2 controllers, the gamepad API say that : 
![image](https://user-images.githubusercontent.com/26094902/41935310-323a9746-7957-11e8-8072-96a8697fbebb.png)

**Comment by wmurphyrd** [comment]
@WellanDraco this was an issue in A-Frame 0.8.0 and has been resolved. Please update to A-Frame 0.8.2
