### ISSUE TITLE
How to set grabbable with rotation without allowing for collisions?

### ISSUE THREAD

**Issue by koganei** [wmurphyrd/aframe-super-hands-component#131]
Hi all,
I'm trying to make an entity grabbable so that I can change its position and rotation, but as soon as I hit it with the controllers, it starts moving away. As soon as I let it go, it keeps the momentum of the movement that it had while I was moving it around. Any way I can prevent the physics from affecting the grabbed entity except for when I'm grabbing it?

**Comment by wmurphyrd** [comment]
I feel your pain! I made another library to address this: https://github.com/wmurphyrd/aframe-physics-extras

Set `collistion-filter="collisionForces: false"` to allow your controllers to ghost through other objects. You can even toggle this, e.g. based on a button press, to allow selective pushing of other objects (inspired by A Chair in A Room's awesome UX). [Example Here](https://wmurphyrd.github.io/aframe-physics-extras/examples/#collisionresponse)
