### ISSUE TITLE
Should be right instead of right-controller?

### ISSUE THREAD

**Issue by brucelane** [wmurphyrd/aframe-super-hands-component#132]
Hi, 
if I put this from the portals.html example <a-entity id="right" hand-controls="right-controller"></a-entity> instead of hand-controls="right", I got "t" is not defined error in the console.

**Comment by PButcher** [comment]
I see no such code in that example (https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/examples/portals.html).

Can you clarify which app you're looking at please?

**Comment by brucelane** [comment]
it's in the mouse/index.html file called by portals.html: https://github.com/wmurphyrd/aframe-super-hands-component/blob/06469351ecf1b3211e1dd490faf9acd4a7a73002/examples/mouse/index.html#L31

**Comment by wmurphyrd** [comment]
Hi Bruce, could you share your code that is having the error?

**Comment by brucelane** [comment]
Hi Will, it's only by trying your samples from https://github.com/wmurphyrd/aframe-super-hands-component/blob/06469351ecf1b3211e1dd490faf9acd4a7a73002/examples/mouse/index.html#L31

**Comment by wmurphyrd** [comment]
I don't see the same error when running the example here. The highlighted code `class="right-controller"` is just setting the vanilla HTML `class` attribute so that `progressive-controls` can find it (and then add on all of the controller components)

**Comment by brucelane** [comment]
ok, I think we can close this
