### ISSUE TITLE
3d models

### ISSUE THREAD

**Issue by IlaRistola** [wmurphyrd/aframe-super-hands-component#133]
Is it possible to use component straight for 3d model (gltf etc.)?
I try it, but cursor not find model at all. I made fast solution for that by make 3d model child of transparent a-box. Not so charming, but works 😄

**Comment by wmurphyrd** [comment]
It can work with 3D models, as long as the collision detection component can handle your model. If you are using gaze cursor or laser pointer mode, that would be the A-Frame [raycaster](https://aframe.io/docs/0.8.0/components/raycaster.html) or with touch mode that would be [sphere-collider](https://github.com/donmccurdy/aframe-extras/blob/master/src/misc/sphere-collider.js)

**Comment by IlaRistola** [comment]
Thx, that works!
Shame on me of course it's about collision detection.
By the way I really like that component 😃
