### ISSUE TITLE
Combining progressive-controls + a-locomotor + physics

### ISSUE THREAD

**Issue by senritsu** [wmurphyrd/aframe-super-hands-component#135]
Is there an example on making this work? Is it supposed to work?

I tried every permutation of `progressive-controls`, `a-locomotor` and manual or autogenerated child entities and cameras, but i just can't figure it out.

Using Oculus Rift + Touch for testing at the moment, can try on Vive as well if necessary.

Having the `a-locomotor` inside of the `progressive-controls` entity with explicit `.right-controller` and `.left-controller` children nested below the locomotor (taken from the defaults in the readme) is the closest i got, in this case the *right* controller works as intended (being able to translate yourself) but the *left* controller doesn't, neither for translation nor for scaling when it is enabled.

```html
      <a-assets>
        <a-mixin id="touch"
                 physics-collider
                 static-body="shape: sphere; sphereRadius: 0.02"
                 super-hands="colliderEvent: collisions;
                              colliderEventProperty: els;
                              colliderEndEvent: collisions;
                              colliderEndEventProperty: clearedEls"
                 collision-filter="group: hands; collidesWith: default; collisionForces: false" />
        <a-mixin id="interactable"
                 dynamic-body
                 collision-filter="collidesWith: default, hands"
                 grabbable="startButtons: triggerdown; endButtons: triggerup" />
        <a-mixin id="static"
                 static-body />
      </a-assets>

      <a-entity progressive-controls="touchMixin: touch; override: true">
        <a-locomotor horizontal-only="false"
                  grabbable="startButtons: gripdown; endButtons: gripup"
                  stretchable="startButtons: gripdown; endButtons: gripup">
          <a-camera>
            <a-entity class="gazecaster"></a-entity>
          </a-camera>
          <a-entity class="right-controller"></a-entity>
          <a-entity class="left-controller"></a-entity>
        </a-locomotor>
      </a-entity>
```

Without having explicit controller child nodes, the locomotor does not work at all.

Having the `a-locomotor` outside of the `progressive-controls` does not work at all.

Previously without the `progressive-controls` with manual `super-hands` on the controllers the locomotion worked as expected (obviously not progressive, but that is fine for now) but the physics colliders did not scale properly with the scaling locomotion, prompting me to try all sort of things to get this working.

Is there a working example that combines physics, `a-locomotor` and `progressive-controls` anywhere? Where have i screwed up?

Bonus question: With the setup snippet above the translation is very jittery, in the previously working version without `progressive-locomotion` it was fairly smooth. What could be the cause for that?

**Comment by wmurphyrd** [comment]
Howdy. I have to confess I've never tried combining them. Have you tried with the locomotor and progressive controls on the same entity?

```html
        <a-locomotor progressive-controls="touchMixin: touch; override: true"
                  horizontal-only="false"
                  grabbable="startButtons: gripdown; endButtons: gripup"
                  stretchable="startButtons: gripdown; endButtons: gripup">
          <a-camera>
            <a-entity class="gazecaster"></a-entity>
          </a-camera>
          <a-entity class="right-controller"></a-entity>
          <a-entity class="left-controller"></a-entity>
        </a-locomotor>
```

As for why the physics bodies weren't scaling, I have [a fix](https://github.com/wmurphyrd/aframe-super-hands-component/commit/5b896010c7b79ea594df69eb6044f0beecf3ea52) for scaling complex and nested physics bodies on the [master branch](https://github.com/wmurphyrd/aframe-super-hands-component/commit/5b896010c7b79ea594df69eb6044f0beecf3ea52). It is stable at present, and I am working towards a (long overdue) fresh release. 

Also, maybe check out [aframe-camera-transform-controls-component](https://github.com/fernandojsg/aframe-camera-transform-controls-component) by @fernandojsg as a more polished alternative to `a-locomotor` (although I haven't tried combining it with `super-hands` yet - if you go that route and have trouble, I would want to help troubleshoot to get them compatible)

**Comment by senritsu** [comment]
To be honest i hadn't even thought of putting them on the same entity, but after a quick try just now it doesn't seem to make a difference.

Thanks for the info though about the scaling fix, and i will certainly try the mentioned component. I will get back to you with my experiences.

**Comment by senritsu** [comment]
@wmurphyrd You may be pleased to hear that [aframe-camera-transform-controls-component](https://github.com/fernandojsg/aframe-camera-transform-controls-component) seems to work without issue with super-hands. It took a bit of finagling and studying the source and examples to get it to work.

A working setup starting from the complete default super-hands DOM using it:

```html
<a-scene environment physics="debug: true" camera-transform-controls>
      <a-assets>
        <!-- ... -->
      </a-assets>

      <a-entity id="cameraRig" progressive-controls="touchMixin: touch; override: true">
      <!-- <a-entity id="cameraRig"> -->
        <a-camera id="camera">
          <a-entity class="gazecaster"></a-entity>
        </a-camera>
        <!-- <a-entity id="righthand" hand-controls="right" class="right-controller"></a-entity> -->
        <a-entity id="righthand" camera-transform-controls-hand="hand:right" class="right-controller"></a-entity>
        <!-- <a-entity id="lefthand" hand-controls="left" class="left-controller"></a-entity> -->
        <a-entity id="lefthand" camera-transform-controls-hand="hand:left" class="left-controller"></a-entity>
      </a-entity>
</a-scene>
```

The important key parts are all `id`s on the entities, the library currently has no robust method of sourcing the camera or controllers and gets them by hardcoded `id`, as well as the `camera-transform-controls-hand` component on the hand entities, something that is not apparent from the readme but can be found in the examples (and the source).

The collider scaling issue is obviously still there, but disregarding that it works pretty much as expected.

**Comment by wmurphyrd** [comment]
Thanks for reporting back. I think I'll move towards retiring `a-locomotor` and recommending this instead. Perhaps we can contribute to make it easier to use as well.

**Comment by senritsu** [comment]
I wouldn't mind porting a similar solution that is tailored specifically to be easy to setup with super-hands as a replacement for the `a-locomotor`, the actual logic of the component is not that complicated and i do have some experience with similar stuff in other platforms. I will open a pull request if i have something ready :)

**Comment by wmurphyrd** [comment]
Awesome!
