### ISSUE TITLE
Combining interactivity levels: point + touch

### ISSUE THREAD

**Issue by senritsu** [wmurphyrd/aframe-super-hands-component#136]
So hello, it's me again with another use case deviating from the intended standard: Combined pointer and touch input.

The use case for this would be having pointer interaction for convenient remote pickup of objects, while at the same time having standard intuitive touch controls. 

An example would be the default interaction model of Oculus Home, where you can pick up objects with the laser pointer (object stays position-anchored to the pointer ray at original pickup distance, rotation stays at its original value) and then use analog stick down to move it into your hand where the interaction model switches to touch/grab (object strictly constrained to hand pose, both position and rotation).

From what the readme makes me believe this should not be possible with super-hands in its current form, the example of using pointer mode with 6DOF controllers mentions specifically limiting the maximum interaction level to 3DOF.

Would there currently be a workaround for such a dual input model? From my current (novice) understanding of A-Frame multiple components of the same type are not supported, so just slapping 2 instances of super-hands (with different max levels) on an entity would probably not work. Does super-hands/A-Frame allow multiple instances of hand controllers on different entities, or would these interfere with each other?

PS: From preliminary testing trying to add multiple `super-hands` instances to the scene results in all kinds of interesting artifacts. Definitely not working out of the box.

**Comment by wmurphyrd** [comment]
What the brilliant folks as [Mozilla Hubs](https://github.com/mozilla/hubs) did to implement this is to have one `super-hands` on the controller entity configured for touch collisions, and a child of the controller with the pointer/raycaster and another `super-hands`. They aren't using `progressive-controls`, though, they handle the controller detection and setup themselves. 

A single `super-hands` wouldn't have any problem handling events coming in from both touch colliders and raycasters all on the same entity, except that the colliders and raycasters all use different events so a single config won't catch them all. I'd thought about modifying it to accept an array of potential collider events, but I'd also hoped the various components out there would settle on a common interface and remove the need.

**Comment by senritsu** [comment]
That is very interesting, i didn't realize the hubs source was on github. Thanks for the link 👍 I kind of figured that doing a custom mix setup without `progressive-controls` would probably be the way to go. Good to have something sophisticated for reference.

Having a standard set of events for something basic like collisions would certainly help, really unfortunate that we are not there yet.
