### ISSUE TITLE
aframe-super-hands incompatible with aframe-extras kinematic body physics collisions?

### ISSUE THREAD

**Issue by bizzell** [wmurphyrd/aframe-super-hands-component#137]
Hi.
I've been playing with kinematic bodies and physics collisions using the latest version of aframe-extras. I thought I'd experiment with adding touching, grabbing and other interactions, so I loaded the latest version of super-hands which works great so far - apart from the fact that physics collisions no longer seem work when my 'player' with kinematic body comes into contact with static bodies?
Is this an intended behaviour?

Regards.

**Comment by wmurphyrd** [comment]
Could you share an example?

**Comment by bizzell** [comment]
Hi.
Thanks for your response.
I have  pasted the entire code for the webpage below. 

`<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no,user-scalable=no,maximum-scale=1">
    <title>Walls</title>
    <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
    <script src="https://cdn.rawgit.com/donmccurdy/aframe-extras/v4.1.2/dist/aframe-extras.min.js"></script>
    <script src="https://cdn.rawgit.com/donmccurdy/aframe-physics-system/v3.1.2/dist/aframe-physics-system.min.js"></script>
    <script src="https://unpkg.com/aframe-event-set-component@^4.0.0/dist/aframe-event-set-component.min.js"></script>
    <script src="https://unpkg.com/super-hands@2.1.0/dist/super-hands.min.js"></script>
    
    <script>
       var playerEl,
        pad1,
        posX,
        posZ;
        
    AFRAME.registerComponent('interactive', {
    schema: {
      color: {default: 'red'}
    },

        init: function () {
          var data = this.data;
          var el = this.el;
          var defaultColor = el.getAttribute('material').color;

          setup();

          el.addEventListener('mouseenter', function () {
            el.setAttribute('color', data.color);
          });

          el.addEventListener('mouseleave', function () {
            el.setAttribute('color', defaultColor);
          });

        el.addEventListener('collide', function () {
            console.log('#' + event.detail.target.el.id + ' has collided with body #' + event.detail.body.el.id);   
        event.detail.target.el;  // Original entity (playerEl).
        event.detail.body.el;    // Other entity, which playerEl touched.
        event.detail.contact;    // Stats about the collision (CANNON.ContactEquation).
        event.detail.contact.ni; // Normal (direction) of the collision (CANNON.Vec3).
        });

          el.addEventListener('click', getWeblink);
        }
    });
  
    function getWeblink(event){
        var target = event.currentTarget,
            weblink = target.getAttribute("weblink");
            console.log(weblink);
        if (target.getAttribute("weblink")){window.location = weblink} 
    }

    function setup(){ 
        playerEl = document.getElementById("player");
        playerEl.addEventListener('collide', teleport); 
        purpleSphere = document.querySelector("#purpleSphere");
        purpleSphere.addEventListener('collide', teleport); 
        
    }
        
    function teleport(event) {
        var target = event.currentTarget;
        if(event.detail.body.el.className === "telepad"){
            posX = Math.floor((Math.random() * 40) + -20);
            posZ = Math.floor((Math.random() * 40) + -20);
            target.setAttribute("position", {posX: 0, y: 1.5, z: posZ});
            console.log('posX ' + posX);
            console.log('posY ' + posZ);
            console.log(event.detail.body.el.className);
            console.log(target.getAttribute("position"));
        }
        
    }
        
    /*function hitTest(event){ 
        console.log('#' + event.detail.target.el.id + ' has collided with body #' + event.detail.body.el.id);   
        event.detail.target.el;  // Original entity (playerEl).
        event.detail.body.el;    // Other entity, which playerEl touched.
        event.detail.contact;    // Stats about the collision (CANNON.ContactEquation).
        event.detail.contact.ni; // Normal (direction) of the collision (CANNON.Vec3).
    }*/
      
    </script>
    
  </head>
  <body>
    <a-scene physics="" renderer="gammaOutput: true">
        <a-assets>
        <a-mixin id="telepad" geometry="primitive: cylinder; radius: 1; height: 0.5" static-body material="color:#FFFFFF" interactive="color: red"></a-mixin>
        <a-mixin id="marker"
                position="10 9." 
                color="black"
                geometry="primitive:ring" 
                material="color: ghostwhite; opacity:0.4"
                interactive="color: red">
        </a-mixin>
        <a-mixin id="gazer" collision-filter="collisionForces: false"></a-mixin>
        <a-mixin id="pointer" collision-filter="collisionForces: false" 
                 teleport-controls="cameraRig: #player; collisionEntities: #teleport-range">
        </a-mixin>
        <a-mixin id="ctrlr" physics-collider collision-filter="collisionForces: false"
                 super-hands="colliderEvent: collisions; colliderEventProperty: els; colliderEndEvent: collisions; colliderEndEventProperty: clearedEls"
                 teleport-controls="cameraRig: #player; collisionEntities: #teleport-range">
        </a-mixin>
        <a-mixin id="collider-space" static-body material="visible:false"></a-mixin>
      </a-assets>
      
      <a-entity id="player" movement-controls kinematic-body>
        <a-entity id="camera"
                  camera    
                  position="0 1.6 0"
                  look-controls="pointerLockEnabled: true"
                  progressive-controls="objects: [grabbable], [droppable], [clickable]; gazeMixin: gazer; pointMixin: pointer; touchMixin: ctrlr">
                    <a-entity cursor position="0 1.6 -1">
                    </a-entity>
        </a-entity>
      </a-entity>
      
      <a-grid static-body></a-grid>
      <a-sphere id="purpleSphere"
               weblink="http://www.thehool.com"
               interactive="color: blue"
               radius="1" height="1"
               position="10 6.5 0" 
               rotation="-0 0 0" 
               color="#bf00ff"
               dynamic-body="mass:1"
               constraint="type: lock;
                           target: #yellowBox;
                           maxForce: 0.1"
               grabbable 
               draggable>
        </a-sphere>
        
        <a-box id="yellowBox" 
                    position="10 0.5 0" 
                    width="2" height="6" depth="2"
                    color="#FFC65D"
                    shadow   
                    static-body>
        </a-box>
        
        <a-text mixin="marker" value="P1" rotation="0 0 0" width="40" align="center" ></a-text>
        <a-text mixin="marker" value="P1" rotation="0 -90 0" width="40" align="center"></a-text>
        <a-text mixin="marker" value="P1" rotation="0 -45 0" width="40" align="center"></a-text>
        <a-text mixin="marker" value="P1" rotation="0 180 0" width="40" align="center"></a-text>

      
      <a-cylinder class="telepad" mixin="telepad" position="8 0.5 -7" ></a-cylinder>
      <a-cylinder class="telepad" mixin="telepad" position="4 0.5 7" ></a-cylinder>
      <a-cylinder class="telepad" mixin="telepad" position="-8 0.5 7" ></a-cylinder>
      <a-cylinder class="telepad" mixin="telepad" position="20 0.5 -9" ></a-cylinder>
      <a-cylinder class="telepad" mixin="telepad" position="1 0.5 14" ></a-cylinder>

      
      <a-box class="wall" color="#39BB82" width="15" height="5" depth="1" position="8 2.5 -10" static-body="" rotation="" scale="" visible="" material="" geometry=""></a-box>
      <a-box class="wall" color="#39BB82" width="15" height="5" depth="1" position="8 2.5 10" static-body="" rotation="" scale="" visible="" material="" geometry=""></a-box>
      <a-box class="wall" color="#39BB82" width="15" height="5" depth="1" position="16 2.5 0" static-body="" rotation="0 90 0" scale="" visible="" material="" geometry=""></a-box>
        
      <a-box class="wall" color="#39BB82" width="15" height="5" depth="1" position="9 2.5 -28" static-body="" rotation="" scale="" visible="" material="" geometry=""></a-box>
      <a-box class="wall" color="#39BB82" width="15" height="5" depth="1" position="8 2.5 20" static-body="" rotation="" scale="" visible="" material="" geometry=""></a-box>
      <a-box class="wall" color="#39BB82" width="15" height="5" depth="1" position="16 2.5 -20" static-body="" rotation="0 90 0" scale="" visible="" material="" geometry=""></a-box>

      
      <a-light type="ambient" color="#bbb" position="" rotation="" scale="" visible="" light=""></a-light>
      <a-light color="#ccc" position="0 30 0" distance="100" intensity="0.4" type="point" rotation="" scale="" visible="" light=""></a-light>
      <a-light color="#ccc" position="3 10 -10" distance="50" intensity="0.4" type="point" rotation="" scale="" visible="" light=""></a-light>
    <canvas class="a-canvas" data-aframe-canvas="true" width="4116" height="2292" style="width: 2058px; height: 1146px;"></canvas><div class="a-enter-vr" aframe-injected=""><button class="a-enter-vr-button" aframe-injected=""></button></div><div class="a-orientation-modal a-hidden" aframe-injected=""><button aframe-injected="">Exit VR</button></div></a-scene>
  </body>
</html>`

In the previous version of this test the kinematic body 'player' collides with static bodies just fine and reports it in the browser console. But since I added super hands the player no longer does... 

Seems like the movement-controls for the "player" entity and the progressive-controls for the "camera" entity conflict?

Any clues would be welcome.
Thanks.

**Comment by wmurphyrd** [comment]
Ah, that helps! You should put `progressive-controls` up one level on `#player`. As it is now, the component is creating a second camera inside your camera and activating that one, which doesn't have `kinematic-body` . You could see this in the [A-Frame inspector](https://aframe.io/docs/0.8.0/introduction/visual-inspector-and-dev-tools.html).
