### ISSUE TITLE
Compatiblity issue : aframe 0.7 and "progressive-controls updates" in v2.1.0

### ISSUE THREAD

**Issue by WellanDraco** [wmurphyrd/aframe-super-hands-component#138]
Hi !
I used the advised version for 0.7 (v2.1.0) but the detection of controler is broken without any loged errors.
Is there a way to bypass ?

tests with Oculus Go = In 0.8 it works well but i'm stuck in 0.7 for compatibility with other components.

**Comment by wmurphyrd** [comment]
Oculus Go controller support isn't included in A-Frame 0.7. You need to import the [`oculus-go-controls` component](https://github.com/aframevr/aframe/blob/master/src/components/oculus-go-controls.js) and then add `oculus-go-controls` to your `.right-controller` entity

```
<a-entity progressive-controls>
 <a-entity class="right-controller" oculus-go-controls></a-entity>
</a-entity>
```
