### ISSUE TITLE
Strange behavior with Go controller and videosphere

### ISSUE THREAD

**Issue by WellanDraco** [wmurphyrd/aframe-super-hands-component#139]
versions : aframe 0.8.2 and superhand ^2.1.0

when entering vr the first time, the border of the Gearvr 3D model is blocky and the laserbeam is behind the video-sphere even if it is enormous...
After that, every time i enter back vr a, fake shadow laser is placed where my controller was and move like it is connected to my head. It replace my controller and everything act as if the real controller and the  real laser are behind the video-sphere.

too bad : i cant take pictures while in vr in oculus go :/ 

the scene : 

   ```
 <a-assets>
      <video id="Background" muted autoplay src="../video/MaryOculus.mp4" loop></video>
  </a-assets>
        <a-entity id="cameracontrolers" progressive-controls="maxLevel:point;objects: .interactive" ></a-entity>
    <a-videosphere src="#Background"></a-videosphere>
```

**Comment by WellanDraco** [comment]
The issue wasnt a bug from Super hand but from the model rendering and a rendering issue of videosphere fixed since...

**Comment by wmurphyrd** [comment]
Thanks for following up!
