### ISSUE TITLE
SH try to place unexisting controllers

### ISSUE THREAD

**Issue by WellanDraco** [wmurphyrd/aframe-super-hands-component#140]
with the oculus CV1 (no controlers but a remote), the gamepad api generate controllers associated to a hand, without position and orientation.

Causing Superhand to generate 2 fake touch controlers spining on themself, or in the same position without moving at all or a gearvr controler;  (every case depend on the use case)

**Comment by wmurphyrd** [comment]
I think this is the same as #128 . Please reopen if you experience this while using A-Frame v0.8.2

**Comment by WellanDraco** [comment]
![image](https://user-images.githubusercontent.com/26094902/42100277-c56d5aac-7b8d-11e8-8c2a-df8d499b361f.png)

On this picture, the CV1 is detected.
My suggestion is to detect "gamepads[i].pose.hasOrientation != false" before  adding the controler if it is not already done.

**Comment by wmurphyrd** [comment]
Thanks for the update. `super-hands`does not handle the gamepad api directly, so this appears to be an issue with the `oculus-touch-controls` component in A-Frame. Please report it there https://github.com/aframevr/aframe/issues

If you just want to support the rift without controllers, you can remove `progressive-controls` and use `super-hands` directly instead
