### ISSUE TITLE
Distinguish between right/left controller

### ISSUE THREAD

**Issue by gabrieljbaker** [wmurphyrd/aframe-super-hands-component#141]
Greetings! I'm using a VR headset with two controllers and I'm trying to use the default pointMixin for the right controller and the default touchMixin for the left controller.  This way, I'd be able to use one hand for laser-controls interaction and the other for closer grabs using a sphere-collider.

I haven't been able to figure out how to do this because of the way the controllers get created automatically. Is there any way to give the right controller a separate mixin as the left controller?

**Comment by WellanDraco** [comment]
you could write a component that listens the event "controller-progressed" on the element, then get all the controllers, select the one you are looking for and then set the specific mixin you want.

**Comment by wmurphyrd** [comment]
Hi Gabe. For this level of complexity, I would just copy the progressive-controls component source into your project and modify it. In the `setLevel` method, the controller hand ('left' or 'right') is already available via the `hand` argument, so you could add a simple check to pick a different mixin
