### ISSUE TITLE
mouseout event not firing and other glitchs

### ISSUE THREAD

**Issue by WellanDraco** [wmurphyrd/aframe-super-hands-component#145]
aframe 0.8.2 and lastest superhand component
I have lots of elements on the scene with the hoverable and clickable component.
every one listens mouseup,mousedown,mousehover and mouseout
every one fire (with bugs) except mouseout.

![image](https://user-images.githubusercontent.com/26094902/42424030-51b1cfde-82d2-11e8-876b-b28132615984.png)

the other bugs are that events are fired to much times for every interaction...

![image](https://user-images.githubusercontent.com/26094902/42424004-f507bb7c-82d1-11e8-9096-fad85b9e6a87.png)

**Comment by wmurphyrd** [comment]
I'm thinking of dropping the global event handler support and using only the custom gesture events to make super hands more efficient and maintainable. Could you tell me why you're using the mouse events over the gesture events? That would help inform my decision.

**Comment by WellanDraco** [comment]
For cross-platform compatibility with non-VR uses :  In one project, I have to use the https://github.com/mayognaise/aframe-mouse-cursor-component 
because the users prefer clicking over dragging the cursor to the interactive element.
Worst, I need to play videos on demand, and I need trusted events in VR. 

On another project, I want to send events to interactives HTML elements with https://github.com/mayognaise/aframe-html-shader. 
In this situation, .onmouseout is more convenient than listening to a state change, identifying it and translating to the best dom event. if you can add .onhover or .ongrab, that would be excellent !

for fuse event, there is the situation where some users with some smartphone VR headset can click on the screen, duplicating the intention to click, and the other situation where they can just gaze.

hope it helped you for your decisions :)

**Comment by wmurphyrd** [comment]
Thanks for the details. Most of this can be done with the gesture events.

>For cross-platform compatibility with non-VR uses

With `progressive-controls`, you get the same events on every platform. Both the gesture events (e.g. `'hover-start'`) and their global event handler (GEH) equivalents are fired in all cases. 

>In one project, I have to use the https://github.com/mayognaise/aframe-mouse-cursor-component
because the users prefer clicking over dragging the cursor to the interactive element.
Worst, I need to play videos on demand, and I need trusted events in VR.

They rolled the aframe-mouse-cursor-component functionality into the A-Frame core with `cursor="rayOrigin: mouse"`. If you pair this with `super-hands` instead of the older component, you'll get the behavior you want, including fusing, without the bugs and errors (I do this in a production application right now). 

>Worst, I need to play videos on demand, and I need trusted events in VR.

You won't see any difference here - the MouseEvent you get in an `onclick` handler from super hands is artificial and untrusted. However, as both the gesture events and GEH events are created from within a handler for the real trusted event, you can still do things like activate video and audio. 

>In this situation, .onmouseout is more convenient than listening to a state change, identifying it and translating to the best dom event.

Can't argue with this one - that's why I looked set up the GEH integration in the first place


Let me know if switching to the A-Frame cursor works better for you

**Comment by WellanDraco** [comment]
> They rolled the aframe-mouse-cursor-component functionality into the A-Frame core with cursor="rayOrigin: mouse". If you pair this with super-hands

Sure but it triggers 2 events, an event on the cursor and on the raycaster. Is the suppression of the raycaster possible when the cursor is used (or hide the mouse and make the raycaster follow it)? it could be a good use case for non-VR pc users (and magic windows users if mouse cursor worked on smartphone).


>Can't argue with this one - that's why I set up the GEH integration in the first place

For GEH, that's a good job, an addeventlistener is enough for most of the work. the details are just missing :/


> With progressive-controls, you get the same events on every platform. Both the gesture events (e.g. 'hover-start') and their global event handler (GEH) equivalents are fired in all cases.

About this event, click and hover-end, I may have some issues with them,
a new exemple of error :
https://arthur-moug.in/bug-hover.mp4
They fire for no obvious reason on click (00:07).

**Comment by WellanDraco** [comment]
Problem resolved by using raycaster's event and playing with event listeners

```
     function clicked(evt) {
        // click on the vr input
        if (tempo == false) {

         // yeay a true click !!!!!

          tempo = true;
          setTimeout(function() {
            // prevent flood
            tempo = false;
          }, 200);
        }
      }

      // netoyage des events superflux
      el.addEventListener("raycaster-intersected", function() {
        console.log("addlistener");

        el.addEventListener("click", clicked);
      });

      el.addEventListener("raycaster-intersected-cleared", function() {
        console.log("removelistener");
        el.removeEventListener("click", clicked);
      });

```
As this solution is only a workaround and not resolve Superhand issue, I might let this issue open :/
before I found the workaround, there where some stack errors at line 445, 161 and 459...

**Comment by WellanDraco** [comment]
hi back,
I have found a workaround that resolves my issues : 
it's using raycaster events and playing with event listeners.

```
      function clicked(evt) {
        // click on the vr input

        if (tempo == false) {

           // an actual click happened

          tempo = true;
          setTimeout(function() {
            // prevent flood
            tempo = false;
          }, 200);
        }
      }

      // netoyage des events superfluxs
      el.addEventListener("raycaster-intersected", function() {
        console.log("addlistener");

        el.addEventListener("click", clicked);
      });

      el.addEventListener("raycaster-intersected-cleared", function() {
        console.log("removelistener");
        el.removeEventListener("click", clicked);
      });
```
as it's not a real solution and the still exist, i'm not sure if i should close this...

before my fix, it seems that clicking with SuperHand caused events to call themselves (causing stacks calls) :/

**Comment by WellanDraco** [comment]
Found the issue, I had this
```
           <a-mixin id="progressivecontrolsgazedefault" position="0 0 -0.5" cursor="fuse: true; fuseTimeout: 1000" animation__fusing="property:geometry.radiusInner; from:0.005;to:0;dur:500;delay:500;easing:easeInSine;startEvents:fusing;"
                    animation__click="property:geometry.radiusInner; from:0;to:0.005;dur:50;easing:easeInSine;startEvents:click;"
                    geometry="primitive: ring;radiusOuter: 0.008; radiusInner: 0.005; segmentsTheta: 32" material="color: #000; shader: flat"
                    super-hands="colliderEvent:raycaster-intersection;
                             colliderEventProperty:els;">
                </a-mixin>
                <a-mixin id="progressivecontrolspointdefault" raycaster="showLine:true" super-hands="colliderEvent:raycaster-intersection;
                              colliderEventProperty:els;">
                </a-mixin> 
```
and
` <a-entity id="user" progressive-controls="objects: #recherche, .keyboardKey;maxLevel:point;"></a-entity>`...
when i remove the mixins or use it as [recommended](https://github.com/wmurphyrd/aframe-super-hands-component#customization), everythings work far better !
no anymore flood of errors...
