### ISSUE TITLE
unability to rotate while in windows PC or Magic window mobile and cursor/touch control

### ISSUE THREAD

**Issue by WellanDraco** [wmurphyrd/aframe-super-hands-component#151]
i visited the demo for it, the interaction work great but it would be awesome if the scene can be grabbed for rotation

https://wmurphyrd.github.io/aframe-super-hands-component/examples/mouse/index-mouse.html

exemple via right-click + grab

**Comment by WellanDraco** [comment]
I tested it in mobile, and the device rotation is blocked. Is there a limitation with this use case ?

**Comment by wmurphyrd** [comment]
I don't see how this is related to `super-hands`. You can set up the camera rotation however you want
