### ISSUE TITLE
Arrays not working in start/end buttons properties

### ISSUE THREAD

**Issue by Zetaphor** [wmurphyrd/aframe-super-hands-component#162]
Using A-Frame 0.9.1 with super-hands 3.0.0

Passing a single value to grabStartButtons works fine. Passing a schema array does not.

Example:

This works:
`super-hands="grabStartButtons: triggerdown"`

This does not:
`super-hands="grabStartButtons: triggerdown gripclose"`

When you attempt to use an array no buttons are mapped and grabbing no longer works

**Comment by wmurphyrd** [comment]
Array values need to be comma separated
https://aframe.io/docs/0.9.0/core/component.html#schema_array

**Comment by Zetaphor** [comment]
Yep, I was checking for gripclose instead of gripdown, thanks for the great library!
