### ISSUE TITLE
box is grabbable but sphere is not

### ISSUE THREAD

**Issue by sirkitree** [wmurphyrd/aframe-super-hands-component#163]
When implementing a simple example, I was testing grabbing a box or a sphere. The box is grabbable but the sphere is not.

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>grabbable test</title>
    <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
    <!-- import third-party components -->
    <script src="https://unpkg.com/aframe-layout-component@4.3.1/dist/aframe-layout-component.min.js"></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    <script src="https://cdn.rawgit.com/donmccurdy/aframe-extras/v4.1.2/dist/aframe-extras.min.js"></script>
    <script src="https://unpkg.com/super-hands@3.0.0/dist/super-hands.min.js"></script>

  </head>
  <body>
    <!-- add cursor="rayOrigin: mouse" to a-scene below for desktop testing -->
    <a-scene>
      <!-- desktop cursor -->
      <!-- <a-camera position="0 1.6 0" wasd-controls-enabled="false">
        <a-entity cursor raycaster="objects: .sphere; far: 5"></a-entity>
      </a-camera> -->

      <!-- laser controls -->
      <!--<a-entity laser-controls raycaster="objects: .sphere, .rotation-control; far: 5" line="color: red; opacity: 0.75"></a-entity> -->
      <a-entity sphere-collider="objects: a-box" super-hands hand-controls="left"></a-entity>
      <a-entity sphere-collider="objects: a-box" super-hands hand-controls="right"></a-entity>

      <!-- floor -->
      <a-cylinder
        radius="32"
        height="0.1"
        color="#000"></a-cylinder>

      <!-- sky -->
      <a-sky color="#87ceeb"></a-sky>
      
      <a-sphere radius="0.5" grabbable color="blue" position="1 1 -1"></a-sphere>
      
      <a-box grabbable color="red" position="-1 1 -1"></a-box>
      
    </a-scene>
  </body>
</html>
```

**Comment by wmurphyrd** [comment]
>collider="objects: a-box"

You have set your collider to only detect boxes. Try 
collider="objects: [grabbable]"
To tell it to detect anything with the grabbable component

On Tue, Jul 2, 2019, at 12:14 PM, Jerad Bitner wrote:
> When implementing a simple example, I was testing grabbing a box or a sphere. The box is grabbable but the sphere is not.

> `<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>grabbable test</title>
    <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
    
    <script src="https://unpkg.com/aframe-layout-component@4.3.1/dist/aframe-layout-component.min.js"></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    <script src="https://cdn.rawgit.com/donmccurdy/aframe-extras/v4.1.2/dist/aframe-extras.min.js"></script>
    <script src="https://unpkg.com/super-hands@3.0.0/dist/super-hands.min.js"></script>

  </head>
  <body>
    
    <a-scene>
      
      

      
      
      <a-entity sphere-collider="objects: a-box" super-hands hand-controls="left"></a-entity>
      <a-entity sphere-collider="objects: a-box" super-hands hand-controls="right"></a-entity>

      
      <a-cylinder
        radius="32"
        height="0.1"
        color="#000"></a-cylinder>

      
      <a-sky color="#87ceeb"></a-sky>
      
      <a-sphere radius="0.5" grabbable color="blue" position="1 1 -1"></a-sphere>
      
      <a-box grabbable color="red" position="-1 1 -1"></a-box>
      
    </a-scene>
  </body>
</html>
`

**Comment by sirkitree** [comment]
Ah... wasn't making that connection. Thank you!
