### ISSUE TITLE
Limited functionality on Oculus Quest

### ISSUE THREAD

**Issue by dirkk0** [wmurphyrd/aframe-super-hands-component#165]
First off all - thanks for this component! Great work!
Then: the good news is, it also works on the Oculus Quest browser, the bad news is: only in a limited way.
It seems that the joystick isn't recognized at all. In the 'Custom button mapping' example, I can't grab the spheres, only kick them around.

**Comment by wmurphyrd** [comment]
Hey Dirk. Is there a controller component for the Quest?

**Comment by Utopiah** [comment]
According to https://aframe.io/docs/0.9.0/introduction/vr-headsets-and-webvr-browsers.html#what-are-some-current-headsets yes

**Comment by dirkk0** [comment]
Yes, more info here:
https://github.com/aframevr/aframe/issues/4304#issuecomment-549666418transmit

I used this as starting point for Quest:
https://curious-electric.com/w/experiments/aframe/minimal-quest/

**Comment by wmurphyrd** [comment]
@Utopiah @dirkk0 hmm that table lists compatibility, but I don't see a quest controls component listed in the docs.

If there is a controller component, or you make one, you should be able to just add it to the controller entity alongside super hands

**Comment by kylebakerio** [comment]
Is this fixed / how is support for quest 2 controllers (which I believe are supported with the recent aframe 1.1.0 update)?

(see updated doc for current version: https://aframe.io/docs/1.1.0/introduction/vr-headsets-and-webvr-browsers.html#what-are-some-current-headsets)

**Comment by wmurphyrd** [comment]
@kylebakerio I believe it is working with quest & quest 2, have a go at https://wmurphyrd.github.io/aframe-super-hands-component/examples/physics/ and let me know

**Comment by kylebakerio** [comment]
Will be getting a quest 2 in a couple days, look forward to trying this on my project.

**Comment by kylebakerio** [comment]
@wmurphyrd that example shows up as broken in chrome on my desktop, I see it is using A-Frame 0.8.2 and the webVR polyfill.

```
Uncaught (in promise) TypeError: Cannot read property 'substring' of undefined
```

I've been unable to find any demo with current aframe, unfortunately, I'd love to test this on my quest 2 and implement it into my own app.

**Comment by kylebakerio** [comment]
I did finally find this one updated to the latest aframe when digging around in the folders, and it worked!

https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/examples/super-basic/index.html

I can try to expand off of that extrapolating from other examples.

Would a pull request to update the examples be welcome?

I just know when I tried updating the physics-extras to the latest aframe, it didn't seem to work for some reason, so I wasn't sure what all would be needed.

**Comment by kylebakerio** [comment]
Here I can confirm that the physics stuff is also working in oculus quest 2 and with the latest aframe:

https://glitch.com/edit/#!/pricey-east-guarantee?path=index.html%3A7%3A49

when going to the github.io deployed pages, all demos seem to be older versions, but I can basically copy/paste your demos from the repo into glitch and they work.

**Comment by wmurphyrd** [comment]
@kylebakerio ah thanks for pointing that out about the examples page, I had forgotten to update the build in the repo. fixed now
