### ISSUE TITLE
Unable to "grab" a static-body.

### ISSUE THREAD

**Issue by RGFTheCoder** [wmurphyrd/aframe-super-hands-component#169]
I am unable to grab a static-body, but I am able to stretch it. I'm trying to make a sort of workshop and need it to be movable.

Thanks!

**Comment by kikoano** [comment]
Same here I also need this feature.

**Comment by kylebakerio** [comment]
I'm not super experienced, but... doesn't this mean it should be a dynamic body? Is that not what dynamic-body vs. static-body means?

**Comment by RGFTheCoder** [comment]
I need a body that will stay still unaffected by physics but affect other objects. Making it dynamic gives it gravity and it moves when other objects touch it. You can stretch it, but not move it, which is inconsistent.

**Comment by zql365747776** [comment]
> I need a body that will stay still unaffected by physics but affect other objects. Making it dynamic gives it gravity and it moves when other objects touch it. You can stretch it, but not move it, which is inconsistent.

aframe-physics-extras component may help you.

**Comment by wmurphyrd** [comment]
Static bodies cannot be moved by physics forces (that's the static part), so the default `grabbable` setting to use physics constraints to move them will not work. Instead set `grabbable="usePhysics: never"`

https://github.com/wmurphyrd/aframe-super-hands-component#component-schema-1
