### ISSUE TITLE
hands seem oriented the wrong way after aframe 1.0.1

### ISSUE THREAD

**Issue by 94coug** [wmurphyrd/aframe-super-hands-component#170]
I had to upgrade my project to a newer Aframe in order for the "enter VR" button to work and then noticed that starting with 1.0.1, the super hands seem to be oriented 90 deg off (about z axis) of what I would expect.  Any ideas of a workaround?  Thanks.

Project: https://glitch.com/~brain-lab
(You can pick up the brain with one hand and then point to some of the colored parts with the tip of the index finger of the other hand)

**Comment by JeffreyConnected** [comment]
@94coug I tested this. I was using the Valve Index + desktop FireFox. I didn't notice anything unusual about the hand(s) orientation. I'll test it with my Quest soon and let you know what I find.

**Comment by wmurphyrd** [comment]
Would you please try with the new version (v3.0.1) and the newest A-Frame (v1.0.4) and let me know if this is still an issue?

**Comment by 94coug** [comment]
I was using these script includes, which exhibited the issue.
```
<script src="https://aframe.io/releases/1.0.3/aframe.min.js"></script>
<script src="https://unpkg.com/super-hands@3.0.0/dist/super-hands.min.js"></script>
```
Then I updated to the version numbers you recommended, and now I don't see the hands at all, just Oculus controllers.

**Comment by wmurphyrd** [comment]
@94coug sorry I thought I'd replied to this. 

In your source change 

```
        <a-entity id="rhand" mixin="handMixin"
                  vive-controls="hand: right"
                  oculus-touch-controls="hand: right"
                  windows-motion-controls="hand: right"
                  hand-controls="right">
```

to

 ```
  <a-entity id="rhand" mixin="handMixin"
                  hand-controls="hand: right">
```

The new A-Frame version changed the api for hand-controls, and the other controller components are redundant when you're using hand controls

**Comment by 94coug** [comment]
Thanks, that did it.  I see the hand model looks better in this version as well, cool!
