### ISSUE TITLE
Mouse control with fixed camera and physics

### ISSUE THREAD

**Issue by thomaswaern** [wmurphyrd/aframe-super-hands-component#174]
Is it possible to drag a physics body around with mouse and a fixed camera?

These are my requirements and current setup, which is not working well:
* super-hands (grabbable)
* aframe-physics-system (cannon.js)
* Mouse/touch as cursor (not gazed based)
* Camera fixed without look/orbit controls (placed above movable object, looking down)
* Dynamic body attached to static body with hinge constraint (y-axis)

This is the closest demo I've found, but it's not using a fixed camera facing down:
https://wmurphyrd.github.io/aframe-super-hands-component/examples/physics/index-mouse.html

**Comment by wmurphyrd** [comment]
Yeah the problem with that setup is using the movement of the camera to apply force to move the objects. You'd need to move the `super-hands` component onto a different (invisible) entity that is made to follow the mouse cursor around, or, if you can make it move a **static** body, use a setup like [the non-physics mouse example](https://wmurphyrd.github.io/aframe-super-hands-component/examples/mouse/index-mouse.html) and `grabbable="usePhysics: never"`
