### ISSUE TITLE
New release to support new Three.js APIs

### ISSUE THREAD

**Issue by auriiolym** [wmurphyrd/aframe-super-hands-component#175]
Hi!

Three.js logs warnings when using `Object3D.getWorldQuaternion()` and `Object3D.getWorldPosition()` without using a target, for performance reasons. I see this is fixed in the master branch. Can you publish a new release so these changes are propagated?

In my case this is about the `grabbable` component, but I guess that doesn't really matter.

Cheers 👋

**Comment by wmurphyrd** [comment]
v3.0.1 released. Thanks
