### ISSUE TITLE
grabbing single object from a fake pile?

### ISSUE THREAD

**Issue by kylebakerio** [wmurphyrd/aframe-super-hands-component#187]
Imagine having a 'pile' that looks like, say, 1000 objects, but is actually just 1 model. Now, I want to 'drag' a single item 'from' this pile, and drop it somewhere else.

So, when I start a drag event, I want to drag not the event I aim at, but a generated child object (since I don't want to have an actual thousand objects in my scene).

What's the best way to do something like this? Is this plausible in superhands, or would it require a workaround (or just an update)?

**Comment by wmurphyrd** [comment]
There are several ways you could approach this:

1. Have the pile transform into a single object when grabbed and then spawn a new pile in it's old spot
2. Have the pile be non-interactive, but keep a single object that stays invisible until grabbed in the same space, spawning a replacement when it is taken
3. Make a custom reaction component for the pile that listens for grab events, spawns a single-item `grabbable` child, and then forwards the original `grab-start` as well as the next `grab-end` event to that new child

**Comment by kylebakerio** [comment]
Thanks!
