### ISSUE TITLE
best way to develop 'snap onto place' functionality?

### ISSUE THREAD

**Issue by kylebakerio** [wmurphyrd/aframe-super-hands-component#193]
Say I have a gameboard, and I want to place pieces onto the board, and when I release a piece I am holding over the board it will snap closest possible position it can. What's the best way to do that?

I already have this set up for raycasting from mouse cursor and from a laser-controls cursor and from a gamepad, so I have code to work with.

My current thoughts are to somehow have a raycast projecting down towards the ground out of the piece I'm holding, and treat that as a kind of cursor.

Any other technique that makes more sense here that I don't know of? Or is that a good way to approach it?

**Comment by wmurphyrd** [comment]
@quinn-madson solved this recently for our immersive web chase game, Virtual Reign (part of https://immers.space) - with a case as simple as a game board, you can just calculate the appropriate square from the x/z offsets. 
https://github.com/immers-space/hubs/blob/vreign/src/components/chess-board.js#L595-L608

In the context of `super-hands`, create a component that listens for `grab-end` and then trigger the math (but don't consume/cancel the `grab-end` event, leave it for `grabbable` to consume so that the grab is released)

**Comment by kylebakerio** [comment]
What I mean is, I already have code that calculates x/z offsets from a raycast position hover and move selection on click if it matches the hover (so no surprise last second changes). What I'm unclear about is how I should substitute the raycast. I guess I could actually count the world position of the held stone itself and transpose that to a world position of the board, is what you're saying (right? anyways, seems like the right idea), but I also need a new 'hover trigger'--a bounding box or something that when crossed indicates that the piece is close enough to the board that I should trigger this hover calculation on tick behavior.

This library already does things similar to that. I suppose I'm just new to collision detection, but that's basically what I'm describing. I just need the collision to not cause physics, similar to what already is done with your phase-shift component in your demo.

I think that's pretty much it, right? Set a non-physics collision detection, set the colliding detection bounding box to be a somewhat larger element so that holding stone over the board triggers the psuedo-collision to activate a hover, and the hover on tick is a calculation comparison of the world position of the held element itself transposed onto the placeable intersections.

Cool, I think I can take a stab at tackling this now. Thanks. :)
