### ISSUE TITLE
Physics not working (Tutorial?)

### ISSUE THREAD

**Issue by carlosveny** [wmurphyrd/aframe-super-hands-component#219]
Hello, i'm trying to make a simple example of grabbing a box that has physics. So if you grab it from the ground and leave it in the air it has to go down. The super-hands component lets me grab and scale objects (that works fine) and then I'm using the `aframe-physics-system` which also works because if I place a box (manually from the code, not using superhands) in the air it collapses to the ground. The thing is when I try to combine physics and superhands. I can't grab the box that is in the ground that technically has physics. It lets me scale it in the ground but not lift it.
I'm a bit new in this world so if anyone could help me, or at least provide me with a simple example of superhands working with physics it would be awesome.
Thank you.

**Comment by carlosveny** [comment]
Nevermind, I was missing the tag `static-body` on the hands component. Now it works well.
This question in StackOverflow (https://stackoverflow.com/q/64902347) help me look in the right direction. I'll leave it here for anyone that has the same problem

**Comment by wmurphyrd** [comment]
Also check out this tutorial from @kylebakerio : https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/getting-started.md
