### ISSUE TITLE
Crawling Cursor support

### ISSUE THREAD

**Issue by HAZARDU5** [wmurphyrd/aframe-super-hands-component#54]
Just wondering if there's any plans to integrate crawling cursor support now that mouse controls are supported? https://github.com/jujunjun110/aframe-crawling-cursor

Would it be possible to attach the `super-hands` component to the crawling cursor itself (which should have a `sphere-collider` attached to it), while still being able to watch for `mousedown` and `mouseup` clicks for grab start/end or drag start/end?

**Comment by HAZARDU5** [comment]
After further investigation, it seems this is possible without any modifications by using `crawling-cursor` in this way:

```
<a-ring id="my-cursor" radius-inner="0.05" radius-outer="0.1" sphere-collider="objects:.cube; radius: 0.1" lerp="properties: position, rotation"  super-hands="grabStartButtons: mousedown; grabEndButtons: mouseup;" static-body="shape: sphere; sphereRadius: 0.02;"></a-ring>
<a-entity camera raycaster universal-controls crawling-cursor="target: #my-cursor">
```
(note: for the above the `static-body` component only needs to be set if using the physics component. I'm also using the `lerp` component for smoothing out the position and rotation of the `crawling-cursor`)

You also have to watch for clicks on the `window` in JS and trigger the `onGrabStartButton()` and `onGrabEndButton()` methods of the `super-hands` component manually though:

```
window.addEventListener('mousedown',function(e){
            this.cursorEl.components['super-hands'].onGrabStartButton();
}.bind(this));

window.addEventListener('mouseup',function(e){
            this.cursorEl.components['super-hands'].onGrabEndButton();
}.bind(this));
```
Hopefully this helps someone!

**Comment by wmurphyrd** [comment]
So it looks like the only thing keeping crawling cursor form working correctly with the cursor-nested-inside-camera setup, which makes the events propagate as expected, is confusion over global coordinates versus local coordinates + parent object offsets in the `crawling-cursor` component. 

If you nest the cursor further within an entity that offsets the camera height, it seems to work:

```html
      <a-camera raycaster crawling-cursor>
        <a-entity position="0 -1.6 0">
          <a-cursor super-hands="colliderEvent: mouseenter;
                                 colliderEventProperty: intersectedEl;
                                 colliderState: cursor-hovered;
                                 grabStartButtons: mousedown;
                                 grabEndButtons: mouseup;
                                 dragDropStartButtons: mousedown;
                                 dragDropEndButtons: mouseup;">

          </a-cursor>
        </a-entity>
      </a-camera>
```

https://steadfast-art.glitch.me
