### ISSUE TITLE
Error calculating the coordinates of the dragged object

### ISSUE THREAD

**Issue by milan-rusev** [wmurphyrd/aframe-super-hands-component#55]
With laser-controls (with Vive, GearVR, Daydream) when dragging an object from distance the dragged object moves more slowly than the raycaster and lags behind it. The reason for that is because the new coordinates of the object are calculated using the coordinates of the hand, and not the intersection point. So the further away you are from the object, the more slowly it moves.

This is the related example: https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/examples/laser/index.html

**Comment by wmurphyrd** [comment]
I think I've got something working for the `pointable` component. Could you try out [laser-pointer controls example](https://wmurphyrd.github.io/aframe-super-hands-component/examples/#laser) now and let me know what you think?

**Comment by milan-rusev** [comment]
@wmurphyrd sorry for the late reply. Unfortunately I no longer have access to headsets with controllers, so I can't test it :(

**Comment by wmurphyrd** [comment]
@milan-rusev no worries! I found a few testers via slack and another issue filer. It works great now, especially with physics included to add in rotation of the grabbed entity. You can view a demo in the examples via motion-capture replay: https://wmurphyrd.github.io/aframe-super-hands-component/examples/laser-physics/
