### ISSUE TITLE
Add support for entity class names in objects list

### ISSUE THREAD

**Issue by HAZARDU5** [wmurphyrd/aframe-super-hands-component#60]
Just wondering if it's possible to add support for targeting entities by their class names in addition to their IDs?

e.g.

```
sphere-collider="objects:#custom-cube,#custom-sphere,.cube,#floor,.sphere"
```

**Comment by wmurphyrd** [comment]
I'm not sure I understand. All CSS selectors work with the `sphere-collider.objects` property and then function with super-hands. I often use attribute selectors in testing, eg 

```
sphere-collider="objects: [grabbable]"
```

**Comment by HAZARDU5** [comment]
Ok, maybe I wasn't doing something quite right. The `[grabbable]` selector seems to work fine - so I'll just use that instead :-)
