### ISSUE TITLE
Incompatible with Uglify.Js?

### ISSUE THREAD

**Issue by JP-Dorman** [wmurphyrd/aframe-super-hands-component#70]
Using this with aframe-react, runs great locally but when building uglify kicks up a fuss:

yarn run v1.0.2
$ react-scripts build
Creating an optimized production build...
Failed to compile.

static/js/main.7a1af631.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/super-hands/index.js:122,0]

**Comment by wmurphyrd** [comment]
I write this in ES6, so you'll need to use babel it to transpile it to ES5 before passing it to uglify. 

If you look that the package.json `dist` script and webpack.config.js in this repo, you can see how I do this for the `super-hands` distribution
