### ISSUE TITLE
Quick tap on mobile screen triggers grab-start twice

### ISSUE THREAD

**Issue by JP-Dorman** [wmurphyrd/aframe-super-hands-component#71]
See live demo: http://jp-dorman.co.uk/aframe_cinema/

There is a counter to the right that increments every time the clickable ">|" button fires the grab-start event.

This works fine on PC but when tested on a phone (OnePlus2 and Samsung GalaxyA5-2015) the function is triggered twice on a quick screen tap and once when slowly held then released.

**Comment by wmurphyrd** [comment]
I think I know what's going on here: [mobile browsers emulate mouse events on a quick tap](https://github.com/aframevr/aframe/pull/2973#issuecomment-323559813) (presumably for compatibility with desktop websites).

I had hoped the `super-hands` state tracking would prevent the double event, but the order they're fired must be such that it starts, ends, and starts again. I'll have to add a check for `AFRAME.utils.device.isMobile()` in the gaze-based controls and unregister the mouse event listeners.

**Comment by wmurphyrd** [comment]
Actually, `isMobile` won't cut it because we also need to consider desktops and tablets with touch. [Turns out this is a really difficult topic](http://www.stucox.com/blog/you-cant-detect-a-touchscreen/)

**Comment by wmurphyrd** [comment]
Ah, [here we go](https://stackoverflow.com/a/14531585/8262231). If we cancel the touch event, then the browser won't fire the mouse events. 

Until I get a patch out, you should be able to fix this in your scene with:

```js
document.querySelector('canvas').addEventListener('touchstart', function (e) { e.preventDefault(); })
```
after the scene has loaded

**Comment by JP-Dorman** [comment]
Been fiddling with it, that line didn't work until I changed it to:

document.querySelector('_a-scene_').addEventListener('touchstart', function (e) { e.preventDefault(); });

So that works great, but then the videos refuse to play. 

Could be wrong but I think it's because most mobile browsers just won't play any video until they've received at least one click for the sake of mobile data saving. (I ran into that problem in my own projects)

**Comment by wmurphyrd** [comment]
Can you tell me what browser you're testing in? I got it to work in your example in firefox desktop (on a windows tablet) by running the the line I posted before in the console.

**Comment by JP-Dorman** [comment]
I'm testing in Chrome for android, it may be specific to that browser?

**Comment by wmurphyrd** [comment]
[This SO comment](https://stackoverflow.com/questions/14530734/handle-both-mouse-and-touch-events-on-touch-screens/14531585#comment78439807_14531585) says we may need to cancel all varieties of touch event for the intended effect. Maybe that differs by browser

**Comment by wmurphyrd** [comment]
I don't have  a new release out, but you can link to the master branch to get this fix immediately

```html
<script src="https://rawgit.com/wmurphyrd/aframe-super-hands-component/master/dist/super-hands.min.js"></script>
```

The issue was that I had to cancel all 3 touch events to keep the mobile browsers form emulating mouse events

**Comment by JP-Dorman** [comment]
That's great, but I'm testing it now and that solution then breaks videos playing in mobile browsers on phones. You need to allow at least the first genuine user click for the browser to allow video to play.

This is on chrome and firefox for android.

**Comment by wmurphyrd** [comment]
Can it be configured to use the trusted touch events instead? If I let even
one mouse event go un-cancelled, then browsers will double all of them.

**Comment by JP-Dorman** [comment]
It does seem like video and audio can be activated by user interactions other than clicks:

https://stackoverflow.com/questions/25095769/force-video-autoplay-using-chrome-browser-on-mobile-devices

As a temporary workaround if you add the muted attribute to a video it will still play.
