### ISSUE TITLE
when model:false, nothing grabs

### ISSUE THREAD

**Issue by omgitsraven** [wmurphyrd/aframe-super-hands-component#75]
I'm doing the following to hide the controller model:

```
<a-entity progressive-controls="objects: .grabbableClass">
	<a-entity id="lhand" class="left-controller" oculus-touch-controls="model:false"></a-entity>
</a-entity>
```

However, when I do this, grabbing no longer works (even though pushing still does).

**Comment by wmurphyrd** [comment]
I think `sphere-collider` won't work without some kind of mesh. Are you putting some other model or geometry on the controller entities?

**Comment by omgitsraven** [comment]
I was putting a geometry on an entity INSIDE that one, but you're right, if I put a geometry right on the same entity, it works (even though it ignores that geometry's shape).

`oculus-touch-controls="model:false" geometry="primitive:box;" material="visible:false;"` lets me grab things with no visible controller.

**Comment by wmurphyrd** [comment]
Yeah, `sphere-collider` uses some three.js methods to get the radius from the entity's mesh, so it it skips any entities that don't have one
