### ISSUE TITLE
Using 'physicsBody' property gives weird results

### ISSUE THREAD

**Issue by omgitsraven** [wmurphyrd/aframe-super-hands-component#76]
I'm having a lot of problems trying to use the physicsBody property; depending on exactly what my situation is, it seems to cause really inconsistent things to happen... I'll describe a few situations I've run into here:

1. If no physicsBody property is specified, the controller's collision will use a sphere of a fixed size, and everything will work right (as long as you don't mind the sphere being that size). The hand entities having children makes no difference.
2. If a valid physicsBody property is specified on the progressive-controls component, whatever its value is is ignored, but grabbing stops working.
3. If an empty/gibberish physicsBody property is specified, the collision will fit the entity and all of its children (spherical if it's a sphere, box otherwise, seemingly), but grabbing will only work on controllers with children if the child is LARGER than the geometry specified on the controller entity. Also, a giant collision box will be attached to the user's head.

It goes on like that; it seems to break differently in every new situation I test it in. It seems like there's no workaround case for using a larger collision volume than the default, without having a giant unwanted collision volume stuck on the user's head. (Without that, I could probably use an empty physicsBody property and just manually sync a mesh's position to the controller's position instead of parenting it, as a workaround...)

**Comment by omgitsraven** [comment]
What is the point of attaching a static-body to the camera, anyway? Maybe I'm not understanding how 'gaze' mode is meant to work, but are people actually going to be walking head-first into objects? (Or is it meant to be like a long nose you can poke things with from a distance?)

Regardless, I'm thinking of making a pull request that would remove any static-bodys that had been placed by the previous interactivity level when the level goes up, so there won't still be collision on the user's head once "touch" mode is active... it's just a workaround, but it might be enough for me for now? How does that sound?

**Comment by wmurphyrd** [comment]
Grab works through a physics constraint between two bodies, so gaze view
has to have one on the camera to be able to move things. Removing it when
the controls progress is a good idea

**Comment by wmurphyrd** [comment]
OK so I didn't think through the `physicsBody` property very well. You can't set it in HTML because the parser will just see the physics body properties as properties for `progressive-controls`.

**Comment by omgitsraven** [comment]
I'm not sure I follow -- you mean "you can't set it in javascript" rather than "you can't set it in HTML", right? Like, calling setAttribute wouldn't work, because it parses strings passed to it, but typing out a tag in the source code would work? (Maybe I'm not understanding the issue..)

**Comment by omgitsraven** [comment]
Also: I'm reading the source to figure out how to control the radius that things can be grabbed at (since it seems to be independent of the size of the collider that's used for just shoving things), and I can't quite track it down. It seems like grabbability is signaled by a 'hit' event, but I can't find anything in the source (or in the source of aframe-physics-system) that emits that event -- where should I be looking?

**Comment by vincentfretin** [comment]
@omgitsraven The hit event come from the sphere-collider in aframe-extras.

**Comment by wmurphyrd** [comment]
Thanks for adding your input on the A-Frame PR. I noticed you only mentioned Vive & Rift. If you're only targeting full 6-DOF VR devices, you'd probably find it simpler to use a setup [like this](https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/examples/sticky/index.html#L36-L37). `progressive-controls` adds a lot of complexity to fallback to the lower fidelity devices, but all you need for touch interaction is controller entities with `super-hands` (they don't even need to be wrapped like that example, they can be top-level in the scene)

**Comment by omgitsraven** [comment]
This is what I meant by, I don't quite understand what to take from the examples :) I'm actually still not sure what to do even here -- since I don't want to see the `hand-controls` model, should I put in all three of `oculus-touch-controls`, `vive-controls` and `windows-motion-controls` instead? And then, where do I specify the 'objects' list for what should be grabbable?

If I'm picking your brain, I might as well just lay my use case out -- I just want the ability to pick up and throw physics objects, with a custom controller mesh. (And ideally I'd like to abstract out the controller vendor detection, rather than having to someday edit in a fourth component and so on when some other company comes along eventually...)

I was planning to just patch `hand-controls` to accept a custom mesh and then write the grabbing logic myself, but when I saw that super-hands already did the grabbing stuff I thought it might be simpler... I didn't realise how many things the custom model aspect was going to throw off, heh :) At this point I've just about got everything how I want it, though; the last thing I need to do is figure out the best way to swap hand models whenever the user is trying to grab (regardless of their success, so `grab-start` isn't an option)... I'm sure I'll find something, probably `buttonchanged`, but I'm leaving it until tomorrow for now...
