### ISSUE TITLE
"Progressive controls with physics" example not usable with GearVR

### ISSUE THREAD

**Issue by vincentfretin** [wmurphyrd/aframe-super-hands-component#89]
The "Progressive controls with physics" example https://wmurphyrd.github.io/aframe-super-hands-component/examples/physics/ is not really usable with GearVR/Daydream because when you grab a cube with the laser, the cube stay at the same distance from the controller. You can't possibly drop it on the big cube.

With the "Integration with Global Event Handlers" https://wmurphyrd.github.io/aframe-super-hands-component/examples/events/ example, it works with GearVR, but I'm too close to the cube and practically above it, I can't read the text. It seems that with positional tracking device you are far from the cube, looking at the motion capture.

So the issue for both examples I think is the same, with non positional tracking device, you are too close to the big cube.

**Comment by vincentfretin** [comment]
For the height that is too high on GearVR, it's the following issue https://github.com/aframevr/aframe/pull/3111
For the distance to the cube, I guess with positional tracking you are positioned to z -2 or something like that?

**Comment by vincentfretin** [comment]
The examples works in non vr mode with the cursor on camera though.

**Comment by wmurphyrd** [comment]
With positional, the center of your play space is at z=0.

Could you tweak the positioning of boxes in the examples to find positions where it is reachable in GearVR (but still with Z between 0 and -1.5 so it's reachable for positional users)

**Comment by vincentfretin** [comment]
Ok, I'll try to see that.

**Comment by vincentfretin** [comment]
For the physics example, if I put transformer cube at `position = "0 1.6 -2.6"`, so if I add 1.6 meter, it's working great. But the real issue is that my eyes are at 2x1.6, I'm above the portals which are at 1.6 meter, because of aframevr/aframe#3111 issue. So I'm closing the issue, should be fixed in next aframe release when they switch to WebGLRenderer I guess https://github.com/aframevr/aframe/pull/3152
